import type { ExperienceItem } from './types'

export const experiences: ExperienceItem[] = [
  {
    title: 'Research Engineer',
    organization: 'University of Glasgow',
    location: 'Glasgow, UK',
    period: 'Apr 2025 — Present',
    type: 'academic',
    featured: true,
    description: [
      'Modernising the Glasgow ECG analysis program with deep-learning modules for arrhythmia detection, noise classification, and signal-quality assessment.',
      'Re-engineering legacy interpretation pipelines for dependable, reproducible clinical deployment at the scale of millions of recordings a year.',
    ],
    skills: ['Deep Learning', 'Signal Processing', 'Clinical ML', 'Python'],
  },
  {
    title: 'Chief Technology Officer',
    organization: 'Tycho MedLink',
    location: 'London, UK',
    period: 'Jan 2023 — Nov 2025',
    type: 'industry',
    description: [
      'Co-founded and led development of a VR-based therapeutic application for Seasonal Affective Disorder (SAD).',
      'Raised £100k across two rounds of UKRI funding, backed by UCL and the Cambridge Alumni Accelerator.',
      'Collaborated with UCL Hospitals on small clinical trials demonstrating efficacy.',
      'Designed and built the VR prototype in Unity for Meta hardware, with user metrics.',
    ],
    skills: ['Unity', 'VR / XR', 'Healthcare', 'Startup Leadership'],
  },
  {
    title: 'PhD Researcher',
    organization: "King's College London",
    location: 'London, UK',
    period: 'Jan 2020 — Oct 2024',
    type: 'academic',
    description: [
      'Deep-learning methods for predicting neurodevelopmental phenotypes from neonatal brain connectivity.',
      'Developed explainable-AI techniques (SmoothGrad, Grad-CAM) for neuroimaging.',
      'Part of the Computational Developmental Neuroscience (CoDe Neuro) Lab.',
      'Collaborated with clinicians at the Centre for the Developing Brain.',
    ],
    skills: ['Deep Learning', 'fMRI', 'Graph Neural Networks', 'Explainable AI'],
  },
  {
    title: 'Senior Research Engineer',
    organization: 'Prepaire',
    location: 'Dubai, UAE (Remote)',
    period: 'Oct 2020 — Sep 2021',
    type: 'industry',
    description: [
      'Led development of AI models, including custom LLMs, to automate genomic data-analysis pipelines — improving processing speed by ~40%.',
      'Integrated model-driven solutions into production code with a focus on scalability in high-performance environments.',
    ],
    skills: ['LLMs', 'Genomics', 'PyTorch', 'Production ML'],
  },
  {
    title: 'Teaching Assistant',
    organization: 'Neuromatch',
    location: 'Remote',
    period: 'May 2022 — Jul 2022',
    type: 'teaching',
    description: [
      'TA for the Deep Learning course; organised daily classes, team work, and practical exercises.',
      'Taught computational methods using PyTorch and neuroimaging tooling (FSL, nipype).',
    ],
    skills: ['PyTorch', 'Teaching', 'FSL', 'nipype'],
  },
  {
    title: 'Software Engineer (Research)',
    organization: 'Google Summer of Code',
    location: 'London, UK',
    period: 'Jul 2022 — Sep 2022',
    type: 'academic',
    description: [
      'Developed an API prototype for an infant eye-tracking system.',
      'Mentored by the eye-surgery department of McGill University.',
    ],
    skills: ['Python', 'PyTorch', 'Eye Tracking', 'Medical Devices'],
  },
  {
    title: 'Engineering Editor',
    organization: 'RSIP Vision (Computer Vision News)',
    location: 'Remote',
    period: 'Nov 2019 — Jan 2023',
    type: 'industry',
    description: [
      'Consulting on medical and computer-vision articles.',
      'Monthly review of state-of-the-art computer-vision research for Computer Vision News.',
    ],
    skills: ['Technical Writing', 'Computer Vision', 'Medical Imaging'],
  },
  {
    title: 'Senior Software Engineer (Pipeline)',
    organization: 'Saddington Baynes',
    location: 'London, UK',
    period: 'Jan 2019 — Mar 2020',
    type: 'industry',
    description: [
      'Built AI-driven automation tools (Python, TensorFlow), reducing manual image-processing work by ~50%.',
      'Implemented GPU-accelerated Docker containers for ML models and optimised CI/CD for deployment.',
    ],
    skills: ['TensorFlow', 'Docker', 'CI/CD', 'GPU Computing'],
  },
  {
    title: 'Software Engineer (Linux Kernel)',
    organization: 'Microsoft',
    location: 'UK',
    period: 'Nov 2018 — Jan 2019',
    type: 'industry',
    description: [
      'Enhanced performance and stability of cloud hypervisor systems with kernel-level optimisations in C.',
      'Contributed to R&D of virtualization technologies.',
    ],
    skills: ['Linux Kernel', 'C', 'Hypervisors', 'Virtualization'],
  },
  {
    title: 'Software Engineer (Systems)',
    organization: 'Kano Computing',
    location: 'London, UK',
    period: 'Dec 2016 — Nov 2018',
    type: 'industry',
    description: [
      'Maintained and extended KANO OS, an in-house Linux-based educational operating system.',
      'Wrote system services and Qt/C++ and GTK interfaces.',
      'Built a filesystem-level image-comparison tool, cutting build time from 4 hours to 30 minutes.',
      'Extended the build system with CI/CD and Jenkins.',
    ],
    skills: ['Linux', 'Python', 'Qt', 'C++', 'Docker', 'Jenkins'],
  },
  {
    title: 'Software Engineer (Games & Research)',
    organization: 'University of Athens',
    location: 'Athens, Greece',
    period: 'Mar 2014 — Jan 2016',
    type: 'academic',
    description: [
      'Built “The Magic Potion”, a serious game for children with mild disabilities (Epinoisi R&D project).',
      'Core game design in PyGame and WebGL, with a C++ AI for the main character.',
    ],
    skills: ['PyGame', 'C++', 'WebGL', 'Game Development'],
  },
  {
    title: 'Software Engineer (Embedded Systems)',
    organization: 'INTRACOM Defense Electronics',
    location: 'Athens, Greece',
    period: 'Jul 2009 — Dec 2013',
    type: 'industry',
    description: [
      'Embedded R&D for a military inter-vehicle telecommunications system (WISPR).',
      'Held NATO Security Clearance; debugged FPGA and microcontroller interfaces.',
      'Built an automated test framework in Visual C++ for prototype units.',
      'Verified validation tests to NATO and MIL-STD standards.',
    ],
    skills: ['Embedded', 'FPGA', 'C', 'LabVIEW', 'Military Standards'],
  },
]
